/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package text_blocks;

/**
 * Java 17 LTS 기준 Text Blocks
 * https://docs.oracle.com/en/java/javase/15/text-blocks/index.html
 */
public class App {

    public static void main(String[] args) {

    }
}
