/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package switch_expressions;

import org.junit.jupiter.api.Test;

import java.util.List;
import java.util.stream.Collectors;
import java.util.stream.Stream;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
}
