/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stream_enhancement;

import org.junit.jupiter.api.Test;

import java.util.List;
import java.util.NoSuchElementException;
import java.util.Optional;
import java.util.stream.Collectors;
import java.util.stream.Stream;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void testTakeWhile() {
        var nats = Stream.iterate(1, (var n) -> n + 1);
        assertEquals(
                List.of(1, 2, 3),
                nats.takeWhile((var n) -> n < 4).collect(Collectors.toUnmodifiableList())
        );
    }
}
