/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package switch_expressions;

/**
 * Java 17 LTS 기준 Switch 식 개선사항
 * https://docs.oracle.com/en/java/javase/14/language/switch-expressions.html
 */
public class App {

    enum Distance { RUN_5K, RUN_10K, RUN_HALF, RUN_FULL; }

    void previousSwitch(Distance distance) {
        int price = 0;
        switch (distance) {
            case RUN_5K:
            case RUN_10K:
                price = 50000;
                break;
            case RUN_HALF:
                price = 80000;
                break;
            case RUN_FULL:
                price = 100000;
                break;
            default:
                throw new IllegalStateException("모르는 거리: " + distance);
        }
        System.out.println(distance + " 참가비 => " + price);
    }

    void newSwitchExpression(Distance distance) {
        int price = switch (distance) {
            case RUN_5K, RUN_10K -> 50000;
            case RUN_HALF -> 80000;
            case RUN_FULL -> 100000;
            // default -> throw new IllegalStateException("모르는 거리: " + distance);
        };
        System.out.println(distance + " 참가비 => " + price);
    }

    void newSwitchStatement(Distance distance) {
        int price = 0;
        switch (distance) {
            case RUN_5K, RUN_10K -> price = 50000;
            case RUN_HALF -> price = 80000;
            case RUN_FULL -> price = 100000;
            default -> throw new IllegalStateException("모르는 거리: " + distance);
        };
        System.out.println(distance + " 참가비 => " + price);
    }

    void newSwitchYield(Distance distance) {
        int price = switch (distance) {
            case RUN_5K:
            case RUN_10K:
                yield 50000;
            case RUN_HALF:
                yield 80000;
            case RUN_FULL:
                yield 100000;
            default:
                throw new IllegalStateException("모르는 거리: " + distance);
        };
        System.out.println(distance + " 참가비 => " + price);
    }

    void run() {
        previousSwitch(Distance.RUN_5K);
        newSwitchExpression(Distance.RUN_10K);
        newSwitchStatement(Distance.RUN_HALF);
        newSwitchYield(Distance.RUN_FULL);
    }

    public static void main(String[] args) {
        new App().run();
    }
}
