/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package optional_enhancement;

import org.junit.jupiter.api.Test;

import java.util.NoSuchElementException;
import java.util.Optional;

import static org.junit.jupiter.api.Assertions.*;

class OptionalTest {
    @Test void testIsEmpty() {
        assertTrue(Optional.empty().isEmpty());
        assertThrows(NoSuchElementException.class, () -> Optional.empty().orElseThrow());
    }
}
